name: flutter_resume_builder
description: A resume builder app made with flutter.

publish_to: "none"

version: 0.4.0+7

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.4
  intl: ^0.18.1
  printing: ^5.11.0
  provider: ^6.0.2
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.5
  flutter_iconpicker: ^3.2.4
  flutter_form_builder: ^9.1.1
  font_awesome_flutter: ^10.1.0
  syncfusion_flutter_pdfviewer: ^23.1.39
  syncfusion_flutter_datepicker: ^23.1.39
  flutter_reorderable_grid_view: ^4.0.0
  file_picker: ^5.5.0
  url_launcher: ^6.1.14
  package_info_plus: ^4.1.0
  csv: ^5.0.2
  archive: ^3.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
