name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
              channel: 'stable'
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build web --release --web-renderer=canvaskit --base-href=/flutter_resume_builder/

      - name: Commit and push to published-site branch
        run: |
          cd build
          mkdir web-deploy
          cd web-deploy
          git init
          git config --global user.email plguerra@outlook.com
          git config --global user.name plguerradesigns
          git remote add origin https://${{secrets.commit_secret}}@github.com/plguerradesigns/flutter_resume_builder.git
          git fetch origin published-site
          git switch published-site
          cp -R ../web/* .
          git status
          git add .
          echo ""
          echo "Committing to published-site branch"
          echo ""
          git commit -m "Updated Release"
          git push origin published-site
